### ISSUE TITLE
请考虑移除 README.md 中可能导致误解的描述

### ISSUE THREAD

**Issue by qwqVictor** [DrhyLee/jwxtToiCloud#1]
> 本项目有幸被参考，并经过了多位开发者的适配，适用于多所院校 若您是重庆邮电或福建师范的师生，请移步 https://github.com/qwqVictor/CQUPT-ics 和 https://github.com/payphone-x/FJNU-ics

该段描述极易造成误解，使人误以为 CQUPT-ics 和 FJNU-ics 为参考此项目后制作的。建议对此描述措辞进行修改，谢谢。

**Comment by DrhyLee** [comment]
OK，我已移除，今天下午有个叫junyilou的福建师范同学在issue里发了以下内容：

你好，我是福建师范大学（FJNU）的一名学生。最近我和同学在你的项目基础上制作了FJNU的课表自动生成程序 FJNU-ics，故请求将我们的项目加至 README.md 中。谢谢。

我现在有些费解这位同学的目的🤔不知道你是否认识他

**Comment by DrhyLee** [comment]
平时git用的少，如因为一些我的操作问题造成误会请指出和海涵

**Comment by qwqVictor** [comment]
> OK，我已移除，今天下午有个叫junyilou的福建师范同学在issue里发了以下内容：
> 
> 你好，我是福建师范大学（FJNU）的一名学生。最近我和同学在你的项目基础上制作了FJNU的课表自动生成程序 FJNU-ics，故请求将我们的项目加至 README.md 中。谢谢。
> 
> 我现在有些费解这位同学的目的🤔不知道你是否认识他

junyilou 并非福建师范大学学生，他是重庆邮电大学学生且是 CQUPT-ics 的发起者，我想这是你产生了错误的误解。且该 issue 是在 [junyilou/python-ical-timetable](https://github.com/junyilou/python-ical-timetable) 下发出，你或许是将你 watch 的 repo 误认为是自己的 repo 了。

目前问题基本解决，我关闭 issue。
